// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/account.proto

/*
Package core_auth is a generated protocol buffer package.

It is generated from these files:
	auth/account.proto

It has these top-level messages:
	Account
	RegisterReq
*/
package core_auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Id        string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username  string                     `protobuf:"bytes,2,opt,name=username" json:"username,omitempty" xorm:"varchar(100)"`
	Password  string                     `protobuf:"bytes,3,opt,name=password" json:"password,omitempty" xorm:"varchar(100)"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty" xorm:"TIMESTAMP"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type RegisterReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "core.auth.Account")
	proto.RegisterType((*RegisterReq)(nil), "core.auth.RegisterReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Account, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/core.auth.AuthService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Register(context.Context, *RegisterReq) (*Account, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.auth.AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/account.proto",
}

func init() { proto.RegisterFile("auth/account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x40, 0xd0, 0x5c, 0x24, 0x86, 0x1b, 0x50, 0x94, 0x85, 0x2a, 0x53, 0x27, 0x47,
	0x2a, 0x0b, 0x8c, 0x19, 0x10, 0x7b, 0x60, 0x47, 0xae, 0x73, 0xa4, 0x96, 0x48, 0x1d, 0xec, 0x33,
	0xbc, 0x04, 0x0f, 0x8d, 0x1a, 0xd7, 0x55, 0xbb, 0x30, 0xde, 0x7d, 0xbf, 0x7d, 0x9f, 0x7e, 0x40,
	0x15, 0x78, 0xdb, 0x28, 0xad, 0x6d, 0xd8, 0xb1, 0x9c, 0x9c, 0x65, 0x8b, 0xb9, 0xb6, 0x8e, 0xe4,
	0x1e, 0x54, 0xf7, 0x83, 0xb5, 0xc3, 0x27, 0x35, 0x33, 0xd8, 0x84, 0x8f, 0x86, 0xcd, 0x48, 0x9e,
	0xd5, 0x38, 0xc5, 0x6c, 0xfd, 0x2b, 0xe0, 0xa6, 0x8d, 0xaf, 0xf1, 0x16, 0x32, 0xd3, 0x97, 0x62,
	0x29, 0x56, 0x79, 0x97, 0x99, 0x1e, 0x2b, 0x58, 0x04, 0x4f, 0x6e, 0xa7, 0x46, 0x2a, 0xb3, 0x79,
	0x7b, 0x9c, 0xf7, 0x6c, 0x52, 0xde, 0xff, 0x58, 0xd7, 0x97, 0x97, 0x91, 0xa5, 0x19, 0x9f, 0x00,
	0xb4, 0x23, 0xc5, 0xd4, 0xbf, 0x2b, 0x2e, 0xaf, 0x96, 0x62, 0x55, 0xac, 0x2b, 0x19, 0x4d, 0x64,
	0x32, 0x91, 0x6f, 0xc9, 0xa4, 0xcb, 0x0f, 0xe9, 0x96, 0xeb, 0x67, 0x28, 0x3a, 0x1a, 0x8c, 0x67,
	0x72, 0x1d, 0x7d, 0x9d, 0x19, 0x88, 0x7f, 0x0c, 0xb2, 0x73, 0x83, 0xf5, 0x0b, 0x14, 0x6d, 0xe0,
	0xed, 0x2b, 0xb9, 0x6f, 0xa3, 0x09, 0x1f, 0x61, 0x91, 0x7e, 0xc5, 0x3b, 0x79, 0x6c, 0x47, 0x9e,
	0x9c, 0xaa, 0xf0, 0x64, 0x7f, 0x28, 0xa4, 0xbe, 0xd8, 0x5c, 0xcf, 0xba, 0x0f, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd4, 0x27, 0x1c, 0x85, 0x67, 0x01, 0x00, 0x00,
}
