// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: auth/account.proto

/*
Package core_auth is a generated protocol buffer package.

It is generated from these files:
	auth/account.proto

It has these top-level messages:
	Account
	RegisterReq
*/
package core_auth

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/gogo/protobuf/gogoproto"

import time "time"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Id        int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username  string     `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password  string     `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt *time.Time `protobuf:"bytes,5,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptorAccount, []int{0} }

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type RegisterReq struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptorAccount, []int{1} }

func (m *RegisterReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "core.auth.Account")
	proto.RegisterType((*RegisterReq)(nil), "core.auth.RegisterReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Account, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/core.auth.AuthService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Register(context.Context, *RegisterReq) (*Account, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.auth.AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/account.proto",
}

func init() { proto.RegisterFile("auth/account.proto", fileDescriptorAccount) }

var fileDescriptorAccount = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0xca, 0x9f, 0xd6, 0x91, 0x18, 0x3c, 0xa0, 0x28, 0x4b, 0xa3, 0x4c, 0x59, 0x70,
	0xa4, 0xb2, 0xb0, 0xa1, 0x20, 0x21, 0xf6, 0xc0, 0x8e, 0x1c, 0xe7, 0x70, 0x2c, 0x91, 0x5e, 0x70,
	0xce, 0xf0, 0x1a, 0x88, 0x17, 0xe4, 0x55, 0x50, 0x92, 0xa6, 0xb4, 0x0b, 0x9b, 0x3f, 0xff, 0x3e,
	0xfb, 0x7e, 0x3a, 0x2e, 0x94, 0xa7, 0x26, 0x57, 0x5a, 0xa3, 0xdf, 0x92, 0xec, 0x1c, 0x12, 0x8a,
	0x95, 0x46, 0x07, 0x72, 0x00, 0xf1, 0xda, 0x20, 0x9a, 0x37, 0xc8, 0x47, 0x50, 0xf9, 0xd7, 0x9c,
	0x6c, 0x0b, 0x3d, 0xa9, 0xb6, 0x9b, 0xba, 0xf1, 0xb5, 0xb1, 0xd4, 0xf8, 0x4a, 0x6a, 0x6c, 0x73,
	0x83, 0x06, 0xff, 0x9a, 0x43, 0x1a, 0xc3, 0x78, 0x9a, 0xea, 0xe9, 0x37, 0xe3, 0x17, 0xc5, 0x34,
	0x4c, 0x5c, 0xf2, 0xc0, 0xd6, 0x11, 0x4b, 0x58, 0xb6, 0x28, 0x03, 0x5b, 0x8b, 0x98, 0x2f, 0x7d,
	0x0f, 0x6e, 0xab, 0x5a, 0x88, 0x82, 0x84, 0x65, 0xab, 0x72, 0x9f, 0x07, 0xd6, 0xa9, 0xbe, 0xff,
	0x44, 0x57, 0x47, 0x8b, 0x89, 0xcd, 0x59, 0xdc, 0x71, 0xae, 0x1d, 0x28, 0x82, 0xfa, 0x45, 0x51,
	0x74, 0x96, 0xb0, 0x2c, 0xdc, 0xc4, 0x72, 0x12, 0x97, 0xb3, 0x8e, 0x7c, 0x9e, 0xc5, 0xef, 0x4f,
	0xbf, 0x7e, 0xd6, 0xac, 0x5c, 0xed, 0xde, 0x14, 0x94, 0x3e, 0xf0, 0xb0, 0x04, 0x63, 0x7b, 0x02,
	0x57, 0xc2, 0xfb, 0x91, 0x07, 0xfb, 0xc7, 0x23, 0x38, 0xf6, 0xd8, 0x3c, 0xf2, 0xb0, 0xf0, 0xd4,
	0x3c, 0x81, 0xfb, 0xb0, 0x1a, 0xc4, 0x2d, 0x5f, 0xce, 0xbf, 0x8a, 0x2b, 0xb9, 0x5f, 0xa9, 0x3c,
	0x18, 0x15, 0x8b, 0x83, 0xfb, 0xdd, 0x5a, 0xd2, 0x93, 0xea, 0x7c, 0x94, 0xbe, 0xf9, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0x8e, 0xcc, 0x1c, 0x9c, 0x01, 0x00, 0x00,
}
